### ISSUE TITLE
Inquiry on Implementing Basic Slicing Features Using OAI_slicing_xApp Guide

### ISSUE THREAD

**Issue by LoganCome** [wineslab/OAI-Slicing-Intel#1]
Hello~

We have successfully set up a private base station using OpenAirInterface and are able to connect UE and access the internet through the core network. We are now looking to implement basic slice functionality and have a few questions.

Firstly, we would like to know if the guide provided in OAI_slicing_xApp.md is sufficient to implement real slice functionality, such as controlling UE download speed or other metrics.

Secondly, we noticed that RAN-SIM is mentioned in OAI_slicing_xApp.md. Is this a RAN simulator? If we have already set up a real system based on hardware devices, do we still need to install RAN-SIM? Will it have any impact on the system? Will it run on a simulated or real system?

Finally, as we are still new to this, we would greatly appreciate any guidance you can provide on implementing basic slice functionality.

Thank you for your help.

**Comment by ChengDaHaI** [comment]
Hi, you could follow the new guide [OAI_Slicing_RICBypass.md](https://github.com/wineslab/OAI-Slicing-Intel/blob/NR_UE_multi_pdusession/OAI_Slicing_RICBypass.md) to run OAI gNB with ran slicing function.
