### ISSUE TITLE
Unable to register gNB with slices to CN

### ISSUE THREAD

**Issue by LoganCome** [wineslab/OAI-Slicing-Intel#2]
Dear contributors,

Thank you very much for your excellent work on this project!

I have successfully implemented a static slicing for gNB following the RIC_Bypass_mode_slicing guide, and my UE seems to connect to the gNB and be assigned to the slice correctly. However, I am encountering an issue with gNB registration in the CN during the UE-gNB-CN end-to-end test. Here are the details:

After setting up slicing in the USRP's xxxx.conf file and making corresponding configurations in the CN's amf.template file, I launched both the CN and gNB with these settings. Unfortunately, the gNB fails to register in the CN, and the error seems to relate to PLMN recognition issues, as shown in the following screenshot. Upon launching the UE, it also fails to register. Without the slicing setup (using the original OAI and CN code), both gNB and UE can register and operate normally.

**- gNB slice configuration:**
![7c77a8adf6c424520cebd6e5b550344](https://github.com/wineslab/OAI-Slicing-Intel/assets/118045635/44d3b9b6-b00f-434b-9e98-7ff517d27443)
**- CN slice configuration in the amf.template file:**
![CNSliceConf](https://github.com/wineslab/OAI-Slicing-Intel/assets/118045635/5e6bf85a-2a8b-458a-a285-68469c3e1407)
**- CN issue about the gNB register:**
![CN_AMF_issueShotDraw](https://github.com/wineslab/OAI-Slicing-Intel/assets/118045635/ab29fcf5-0269-4066-aa0d-dc4522b6a8f1)

I have several questions and would greatly appreciate your insights:

1. **For CN:** Have you conducted end-to-end tests involving UE-gNB-CN with the CN included? If so, did you use OAI's CN? Could you please provide details about the CN repository and versions used? In the RIC Bypass mode slicing guide, what additional modifications are necessary for the CN files when slices are added to the gNB's startup file?

2. **For UE:** I am using a Quectel RM520N-GL 5G module and SIM card. Are there specific configurations required for the UE as well? Despite multiple format attempts and contacting the vendor, I keep receiving an error when trying to configure NSSAI (e.g., AT+CGDCONT=4,"IP","internet_EMBB000002","0.0.0.0",0,0,0,0,,,,,,,,0,"01.000002",,,,0). This issue might also be related to the absence of corresponding slices in the CN.

3. **For gNB:** After starting one of the UE’s 5G modules, gNB displays that two UEs have been identified and there is an RNTI change, which disappears when the UE’s module is stopped. Is this normal? Why would two UEs appear in the gNB?

**Experimental Environment:**
- UE: Quectel RM520N-GL
- gNB: Current repository
- CN: OpenXG (Convenient installation version of OAI) available at [OpenXG Repository](https://git.opensource5g.org/openxg/openxg-5gcs-release/-/tree/master)

Additionally, I have recorded the processes for both gNB and CN, detailing the issue:
- gNB process: [[Link to video](https://drive.google.com/file/d/1hgBFfaTJR6CHE56LHFWxr4HvHwQ5qktB/view?usp=sharing)]
- CN process: [[Link to video](https://drive.google.com/file/d/1R35gqKlkpD0c2sANudarC8Q2A444F6oi/view?usp=sharing)]
- Some of screenshots about UE connection in gNB: [[Link to file](https://drive.google.com/drive/folders/1NNtFU2F83tIt4o1cUVdqk5D0PjtbwqBy?usp=drive_link)]

Overall, my UE-gNB with slicing seems to test successfully, but the registration process for gNB (slice)-CN does not succeed. I sincerely request your help in resolving these issues.

Thank you for your attention and assistance!

**Comment by ChengDaHaI** [comment]
Hi,
[docker-compose-2slice.yml.zip](https://github.com/wineslab/OAI-Slicing-Intel/files/15057755/docker-compose-2slice.yml.zip)

1. For you CN, could you try the attached configure file with command `docker compose -f docker-compose-2slice.yml up -d`? It is from official OAI CN repo. You shall make everything work from official OAI repo then test with other third-party code. If the CN is working good (docker ps -a), your gNB should be able to connect to the CN. Also note that there are only two slice configured in the file docker-compose-2slice.yml . You can edit to add more slices accordingly.

2. I have no idea about Quectel 5G Module. You may find useful info from Quectel forum. If you have more than one USRP, you can run OAI nrUE to connect.

3. Two RNTI does not mean exactly two UE. It means that gNB receive two PRACH connections somehow. You could try OAI dev branch with tag 2023.w27 to test if the behavior is from OAI itself or from our customized code.
